import os

MAIN_SERVER_PROTOCOL = os.getenv('MAIN_SERVER_PROTOCOL')
MAIN_SERVER_ADDRESS = os.getenv('MAIN_SERVER_ADDRESS')
MAIN_SERVER_PORT = os.getenv('MAIN_SERVER_PORT')

MAIN_SERVER = f'{MAIN_SERVER_PROTOCOL}://{MAIN_SERVER_ADDRESS}'
if MAIN_SERVER_PORT:
    MAIN_SERVER += f':{MAIN_SERVER_PORT}'
